name: tester
version: 0.0.1
authors:
  - Jonah Williams <jonahwilliams@google.com>

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  shelf: 0.7.5
  stream_transform: 1.2.0
  watcher: '0.9.7+15'
  stack_trace: 1.9.3
  dart_console: 0.6.0
  vm_service: 4.0.4
  package_config: 1.9.3
  uuid: 2.0.4
  args: 1.6.0
  pedantic: 1.9.0
  path: 1.7.0
  analyzer: 0.39.8
  dwds: 3.1.1
  webkit_inspection_protocol: 0.5.4
  _fe_analyzer_shared: 3.0.0
  file: 5.1.0
  process: 3.0.13

dev_dependencies:
  test_shim:
    path: test_shim