name: tester
version: 0.0.1-dev3
repository: https://github.com/jonahwilliams/tester
description: An experimental test framework for Dart & Flutter.

environment:
  sdk: '>=2.9.0-17.0.dev <3.0.0'

executables:
  tester: tester

dependencies:
  meta: ^1.1.8
  devtools_server: 0.2.5
  devtools: 0.2.5
  yaml: 2.2.1
  coverage: 0.14.0
  shelf: 0.7.5
  stream_transform: 1.2.0
  watcher: '0.9.7+15'
  stack_trace: 1.9.3
  dart_console: 0.6.0
  vm_service: 4.1.0
  package_config: 1.9.3
  uuid: 2.1.0
  args: 1.6.0
  pedantic: 1.9.0
  path: 1.7.0
  dwds: 4.0.1
  webkit_inspection_protocol: 0.7.3
  _fe_analyzer_shared: 4.0.0
  file: 5.1.0
  process: 3.0.13

dev_dependencies:
  expect:
    path: ../expect
