name: tester
version: 0.0.3-dev1
repository: https://github.com/jonahwilliams/tester
homepage: https://github.com/jonahwilliams/tester
description: An experimental test runner for Dart & Flutter, designed for iterative workflows.

environment:
  sdk: '>=2.9.0-17.0.dev <3.0.0'

executables:
  tester: tester

dependencies:
  meta: 1.2.2
  yaml: '>=2.2.1 <2.2.2'
  coverage: '>=0.14.0 <0.14.1'
  shelf: '>=0.7.7 <0.7.8'
  stream_transform: '>=1.2.0 <1.2.1'
  watcher: '>=0.9.7+15 <0.9.8'
  stack_trace: '>=1.9.3 <1.9.5'
  dart_console: '>=0.6.2 <0.6.3'
  vm_service: '>=4.1.0 <4.1.1'
  package_config: '>=1.9.3 <1.9.4'
  uuid: '>=2.1.0 <2.1.1'
  args: '>=1.6.0 <1.6.1'
  pedantic: '>=1.9.0 <1.9.1'
  path: '>=1.7.0 <1.7.1'
  dwds: '>=5.0.0 <5.0.1'
  webkit_inspection_protocol: '>=0.7.3 <0.7.4'
  _fe_analyzer_shared: '>=4.0.0 <4.0.1'
  file: '>=5.2.1 <5.2.2'
  process: '>=3.0.13 <3.0.14'
  logging: '>=0.11.4 < 0.11.5'

dev_dependencies:
  expect:
    path: ../expect
