name: Main

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_linux:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Build
        run: dart2native -o linux_tester bin/tester.dart
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: linux_tester
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: DanTup/gh-actions/setup-dart@master
      - name: Install dependencies
        run: pub get
      - name: Build
        run: dart2native -o windows_tester.exe bin/tester.dart
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: windows_tester.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: DanTup/gh-actions/setup-dart@master
      - name: Install dependencies
        run: pub get
      - name: Builds
        run: dart2native -o macos_tester bin/tester.dart
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: macos_tester
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
